### ISSUE TITLE
Feature 1: User can view list of pokemon in a game, and some info on them

### ISSUE THREAD

**Issue by Zach-Giffen** [Zach-Giffen/Pokemon-Team-Builder#1]
## ⚙️ Feature

user can view pokemon, see info on them, and filter what they see

## 📐 Functionality

user will be able to scroll through a list of pokemon and edit which pokiemon appear by changing filters

## 🖼️ Wireframes

<img width="909" alt="image" src="https://github.com/Zach-Giffen/ajax-project/assets/146271458/cdb92064-b161-45b3-9542-ec38753a646a">

## ✅ Task List

- [x] add a div for the header and populate it
- [x] add a form to add filters
- [x] make a function that loops through the pokemon and adds the appropriate ones to a table
  - [x] link to the pokeapi
  - [x] write the function to loop through and make the table as a DOM
  - [x] make a div in the html and appended the DOM to it
- [x] make sure everything is working in mobile and desktop
- [x] remove unnecessary code
- [x] confirm that everything still functions and looks right
