### ISSUE TITLE
Feature 2: User can save pokemon to a team and view various details about them

### ISSUE THREAD

**Issue by Zach-Giffen** [Zach-Giffen/Pokemon-Team-Builder#2]
## ⚙️ Feature

Users can save their pokemon to a team, and view them

## 📐 Functionality

user will click the pokeball to open a modal that will ask them which team to save it to. once they confirm, they can go to the team page, choose a team, and view the pokemon and various stats

## ✅ Task List
- [x] make a modal pop up when the add img is clicked
  - [x] it should say "(pokemon name) was caught" and save their data to local storage
  - [x] if 6 pokemon are already on the team, it will say " (pokemon name) ran away..." and not save it to the local storage
- [x] make the html and css of the team page
  - [x] header will stay the same
  - [x] empty space for team name (will be changeable later)
  - [x] 3 rows, with two divs taking up 50% if width inside each row
  - [x] each div will have a bunch of info on the pokemon. fill the divs with info ion the html so i can style
- [x] populate the divs with pokemon info
  - [x] write dom to what I hardcoded in the div, then delete the hard code. 
  - [x] connect the local storage data to the dom 
- [x] style for mobile
- [x] delete unnecessary code
- [x] double check for functionality
